name: Code Linting on Pull-Requests

on:
  pull_request:
    branches: [ master, release* ]

jobs:
  clang-tidy-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install iceoryx dependencies and clang-tidy
        uses: ./.github/actions/install-iceoryx-deps-and-clang

      - name: Get git diff
        id: changed_files
        uses: Ana06/get-changed-files@v1.2
      - name: diff scan, clang-tidy for all files which are in `.clang-tidy-diff-scans.txt`
        run: |
          for diff_file in ${{ steps.changed_files.outputs.added_modified }}; do
            ./tools/scripts/clang_tidy_check.sh scan_list .clang-tidy-diff-scans.txt ${diff_file}
          done

  check-for-todo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check for todos which are not linked to issues or violating the format @todo iox-#?
        run: ./tools/ci/todo-verificator.sh

  verify-links-in-markdown-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          fail: true
          args: --verbose --no-progress './**/*.md' --github-token ${{secrets.GITHUB_TOKEN}} --max-concurrency 1
